# This is the network config written by 'subiquity'
#network:
#  ethernets:
#    enp0s3:
#      dhcp4: true
#  version: 2
network:
 version: 2
 ethernets:
  enp0s3:
   addresses: [192.168.180.114/24]
   gateway4: 192.168.180.1
   nameservers:
    addresses: [192.168.180.1]
